#!/bin/bash
echo "📊 VERIFICACIÓN DE CORRECCIONES DEL HISTÓRICO POR NÚMERO DE ORDEN"
echo "=================================================================="
echo ""

# Verificar tarjetas estadísticas
echo "🔍 Verificando correcciones de tarjetas estadísticas:"
echo "- Fondo de tarjetas:"
grep -A3 "search-stat {" style.css | grep "rgba.*255.*255.*255.*0.1" || echo "❌ Fondo de tarjetas no corregido"
echo "- Texto de etiquetas:"
grep -A8 "search-stat-label {" style.css | grep "color-text-secondary" || echo "❌ Color de etiquetas no corregido"
echo ""

# Verificar contenedor de tabla
echo "🔍 Verificando contenedor de tabla:"
echo "- Fondo del contenedor:"
grep -A4 "search-table-container {" style.css | grep "rgba.*255.*255.*255.*0.05" || echo "❌ Contenedor no corregido"
echo ""

# Verificar elementos de resaltado
echo "🔍 Verificando elementos de resaltado:"
echo "- Resaltado general:"
grep -A5 "search-highlight {" style.css | grep "color-yellow-400" || echo "❌ Resaltado general no corregido"
echo "- Resaltado de números coincidentes:"
grep -A3 "search-order-match {" style.css | grep "rgba.*45.*212.*191" || echo "❌ Resaltado de números no corregido"
echo ""

# Verificar mensajes de no resultados
echo "🔍 Verificando mensajes de no resultados:"
echo "- Color de texto principal:"
grep -A3 "no-results-message h4" style.css | grep "color-text" || echo "❌ Títulos de no resultados no corregidos"
echo "- Color de texto general:"
grep -A3 "no-results-message {" style.css | grep "color-text-secondary" || echo "❌ Texto de no resultados no corregido"
echo ""

echo "✅ VERIFICACIÓN COMPLETADA"
echo ""
echo "🌐 URL del sitio: https://nomenaments-lleida.web.app"
echo ""
echo "📋 CORRECCIONES APLICADAS:"
echo "- Tarjetas estadísticas: Fondo cambiado a transparencia oscura"
echo "- Etiquetas de tarjetas: Color ajustado para contraste"
echo "- Contenedor de tabla: Fondo transparente oscuro"
echo "- Resaltados: Colores ajustados para visibilidad"
echo "- Mensajes de error: Texto visible en esquema oscuro"
echo ""
echo "🧪 INSTRUCCIONES DE PRUEBA ESPECÍFICAS:"
echo "1. Abre https://nomenaments-lleida.web.app"
echo "2. Haz login y haz clic en el botón 🔍"
echo "3. Busca un número de orden válido (ej: 10524)"
echo "4. Verifica que las tarjetas del resumen son legibles:"
echo "   - 'NOMBRAMIENTOS', 'ESPECIALIDADES', 'MÁS RECIENTE', 'PERIODO'"
echo "5. Verifica que todos los textos tienen buen contraste"
echo "6. Comprueba que los números resaltados son visibles"
echo "7. Prueba una búsqueda sin resultados para verificar el mensaje"
echo ""
